services:
  webapp:
    container_name: contenedor_app
    restart: always
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - database
    networks:
      - app-network
    environment:
      - NODE_ENV=production
  database:
    container_name: contenedorDB
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db
      
networks:
  app-network:
    driver: bridge
    name: patitasfelices_network    

volumes:
  mongodb_data: