services:
  webapp:
    container_name: contenedor_app
    restart: always
    build: .
    ports:
      - "5000:3000"
    links: 
      - database
  database:
    container_name: contenedorDB
    image: mongo
    ports:
      - "27018:27017"